name: Halo Technologies
favicon: null
layout_spectrum: 0.2636
typography_spectrum: 0.73502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f85ae'
    - '#a4a6c4'
    - '#5e5a60'
    - '#e6e6ed'
    - '#c6c6d9'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
